# Answer 1

In [4]:
import numpy as np
x=np.arange(2,50,3)
print(x)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Answer 2

In [8]:
import numpy as np
l1=[]
l2=[]
for i in range(5):
    n1=int(input("Enter values in list 1: "))
    l1.append(n1)
print("list 1: ",l1)
for i in range(5):
    n2=int(input("Enter values in list 2: "))
    l2.append(n2)
print("list 2: ",l2)
a1=np.array(l1)
a2=np.array(l2)
a=np.concatenate((a1,a2))
print("concatenate array: ",a)
s=np.sort(a)
print("sorted array:",s)


Enter values in list 1: 12
Enter values in list 1: 43
Enter values in list 1: 56
Enter values in list 1: 3
Enter values in list 1: 6
list 1:  [12, 43, 56, 3, 6]
Enter values in list 2: 10
Enter values in list 2: 0
Enter values in list 2: 8
Enter values in list 2: 94
Enter values in list 2: 13
list 2:  [10, 0, 8, 94, 13]
concatenate array:  [12 43 56  3  6 10  0  8 94 13]
sorted array: [ 0  3  6  8 10 12 13 43 56 94]


# Answer 3

In [9]:
import numpy as np
arr=np.array([[4,5,6],[3,6,9]])
print("Dimesnions in array: ",arr.ndim)
print("Size of an array: ",arr.size)

Dimesnions in array:  2
Size of an array:  6


# Answer 4

In [13]:
#newaxis snippet
import numpy as np
arr=np.arange(5)
print("Array Shape: ",arr.shape)
row=arr[np.newaxis, :]
print("Rows: ",row.shape)
col=arr[:,np.newaxis]
print("columns: ",col.shape)

Array Shape:  (5,)
Rows:  (1, 5)
columns:  (5, 1)


In [15]:
#expand_dims snippet
import numpy as np
arr=np.arange(5)
print("Array Shape: ",arr.shape)
row=np.expand_dims(arr,axis=0)
print("Rows: ",row.shape)
col=np.expand_dims(arr,axis=1)
print("columns: ",col.shape)

Array Shape:  (5,)
Rows:  (1, 5)
columns:  (5, 1)


# Answer 5

In [21]:
import numpy as np
arr1=np.square([2,4,6,8,10])
arr2=np.square([3,6,9,12,15])
print("Vertical stack: ",np.vstack([arr1,arr2]))
print("Horizontal stack: ",np.hstack([arr1,arr2]))

Vertical stack:  [[  4  16  36  64 100]
 [  9  36  81 144 225]]
Horizontal stack:  [  4  16  36  64 100   9  36  81 144 225]


# Answer 6

In [24]:
import numpy as np
arr1=np.array([2,4,6,8,10,4,8,2,16])
uq,ct=np.unique(arr1,return_counts=True)
arr=np.asarray((uq,ct)).T
print(arr)

[[ 2  2]
 [ 4  2]
 [ 6  1]
 [ 8  2]
 [10  1]
 [16  1]]
